version: "2"
services:
  database:
    image: postgres:12-alpine
    container_name: logproj-database
    restart: always
    volumes:
      - ./docker-sucks-please-ignore/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: logproj
      POSTGRES_PASSWORD: localpw
      POSTGRES_USER: logproj
    expose:
      - "5432"
    ports:
      - "8001:5432"
  web:
    image: logproj
    container_name: logproj
    ports:
      - "8666:8666"
    depends_on:
      - database
